DefaultContentLanguage: de
baseURL: https://buterland-beckerhook.de/
languageCode: de-DE
title: Buterland-Beckerhook
copyright: Buterland-Beckerhook e.V.
theme: bb2018
timeout: 120000
enableGitInfo: true

build:
  writeStats: true

params:
  description: Website des Schützenvereins Buterland-Beckerhook e.V. von 1909 aus Gronau (Westf.)
  mapboxtoken: pk.eyJ1IjoicnZlcnN0YmIiLCJhIjoiY2toMjJpMmZ5MDZoMDJzb2ltNDNoMzUyeCJ9.11ki8zSa9gqp7f3dLPljCQ

outputFormats:
  Calendar:
    protocol: https://

menu:
  main:
    - identifier: home
      name: Der Verein
      url: /
      weight: 1
    - identifier: termine
      name: Termine
      url: /termine/
      weight: 2
    - identifier: aktuell
      name: Aktuelles
      url: /aktuell/
      weight: 3
    - identifier: thron
      name: Thron
      url: /thron/
      weight: 4

  right:
    - identifier: kontakt
      name: Kontaktformular
      url: /kontakt/
      weight: 1
    - identifier: datenschuzerklaerung
      name: Datenschutz
      url: /datenschutzerklaerung/
      weight: 2
    - identifier: impressum
      name: Impressum
      url: /impressum/
      weight: 3
