baseURL: https://buterland-beckerhook.de/
languageCode: de-DE
title: Buterland-Beckerhook
theme: bb2018

params:
  description: Website/App des Schützenvereins Buterland-Beckerhook e.V. von 1909 aus Gronau (Westf.)

menu:
  main:
  - identifier: home
    name: Der Verein
    url: /
    weight: 1
  - identifier: events
    name: Termine
    url: /events/
    weight: 2
  - identifier: reports
    name: Aktuelles
    url: /reports/
    weight: 3
  - identifier: organization
    name: Gremien
    url: /organization/
    weight: 5
  - identifier: thrones
    name: Thron
    url: /thrones/
    weight: 10

  right:
  - identifier: contact
    name: Kontakt
    url: /contact/
    weight: 1
  - identifier: privacy-policy
    name: Datenschutz
    url: /privacy-policy/
    weight: 2
  - identifier: impress
    name: Impressum
    url: /impress/
    weight: 3
