baseURL: https://bb.verst.eu/
languageCode: de-DE
title: Buterland-Beckerhook
theme: bb2018

params:
  description: Website/App des Schützenvereins Buterland-Beckerhook e.V. von 1909 aus Gronau (Westf.)

menu:
  main:
  - identifier: home
    name: Der Verein
    url: /
    weight: 1
  - identifier: organization
    name: Gremien
    url: /organization/
    weight: 5
  - identifier: thrones
    name: Thron
    url: /thrones/
    weight: 10

  right:
  - identifier: privacy-policy
    name: Datenschutz
    url: /privacy-policy/
    weight: 1
  - identifier: impress
    name: Impressum
    url: /impress/
    weight: 2